run:
  deadline: 5m
  allow-parallel-runners: true
  issues-exit-code: 1

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - promlinter
    - staticcheck
    - tagliatelle
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - '(github.com/go-kit/log.Logger).Log'
  lll:
    line-length: 200
  funlen:
    lines: 210
    statements: 50
